package com.catike_mall.domain.entity.normal;

public class Advertise {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column advertise.PK_ID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer pkId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column advertise.NAME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column advertise.ENABLE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Boolean enable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column advertise.POSITION
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column advertise.URL
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column advertise.IMAGE_DIR
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String imageDir;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column advertise.DESCRIPTION
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column advertise.PRICE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Long price;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column advertise.PK_ID
	 * @return  the value of advertise.PK_ID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getPkId() {
		return pkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column advertise.PK_ID
	 * @param pkId  the value for advertise.PK_ID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setPkId(Integer pkId) {
		this.pkId = pkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column advertise.NAME
	 * @return  the value of advertise.NAME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column advertise.NAME
	 * @param name  the value for advertise.NAME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column advertise.ENABLE
	 * @return  the value of advertise.ENABLE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Boolean getEnable() {
		return enable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column advertise.ENABLE
	 * @param enable  the value for advertise.ENABLE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setEnable(Boolean enable) {
		this.enable = enable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column advertise.POSITION
	 * @return  the value of advertise.POSITION
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column advertise.POSITION
	 * @param position  the value for advertise.POSITION
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setPosition(Integer position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column advertise.URL
	 * @return  the value of advertise.URL
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column advertise.URL
	 * @param url  the value for advertise.URL
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column advertise.IMAGE_DIR
	 * @return  the value of advertise.IMAGE_DIR
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getImageDir() {
		return imageDir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column advertise.IMAGE_DIR
	 * @param imageDir  the value for advertise.IMAGE_DIR
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setImageDir(String imageDir) {
		this.imageDir = imageDir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column advertise.DESCRIPTION
	 * @return  the value of advertise.DESCRIPTION
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column advertise.DESCRIPTION
	 * @param description  the value for advertise.DESCRIPTION
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column advertise.PRICE
	 * @return  the value of advertise.PRICE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Long getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column advertise.PRICE
	 * @param price  the value for advertise.PRICE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setPrice(Long price) {
		this.price = price;
	}
}