package com.catike_mall.domain.entity.normal;

import java.util.Date;

public class GoodsInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_info.PK_ID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer pkId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_info.NAME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_info.ENABLE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Boolean enable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_info.PRICE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Long price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_info.COUNT
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_info.IMAGE_DIR
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String imageDir;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_info.STORE_PKID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer storePkid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_info.BRIEF_INTRODUCTION
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String briefIntroduction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_info.EXPOSURE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer exposure;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_info.WEIGHTS
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer weights;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_info.MAKE_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer makeEmp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_info.MAKE_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Date makeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_info.MODIFY_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer modifyEmp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_info.MODIFY_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_info.VER
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer ver;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_info.PK_ID
	 * @return  the value of goods_info.PK_ID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getPkId() {
		return pkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_info.PK_ID
	 * @param pkId  the value for goods_info.PK_ID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setPkId(Integer pkId) {
		this.pkId = pkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_info.NAME
	 * @return  the value of goods_info.NAME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_info.NAME
	 * @param name  the value for goods_info.NAME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_info.ENABLE
	 * @return  the value of goods_info.ENABLE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Boolean getEnable() {
		return enable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_info.ENABLE
	 * @param enable  the value for goods_info.ENABLE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setEnable(Boolean enable) {
		this.enable = enable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_info.PRICE
	 * @return  the value of goods_info.PRICE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Long getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_info.PRICE
	 * @param price  the value for goods_info.PRICE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setPrice(Long price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_info.COUNT
	 * @return  the value of goods_info.COUNT
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_info.COUNT
	 * @param count  the value for goods_info.COUNT
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setCount(Integer count) {
		this.count = count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_info.IMAGE_DIR
	 * @return  the value of goods_info.IMAGE_DIR
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getImageDir() {
		return imageDir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_info.IMAGE_DIR
	 * @param imageDir  the value for goods_info.IMAGE_DIR
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setImageDir(String imageDir) {
		this.imageDir = imageDir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_info.STORE_PKID
	 * @return  the value of goods_info.STORE_PKID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getStorePkid() {
		return storePkid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_info.STORE_PKID
	 * @param storePkid  the value for goods_info.STORE_PKID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setStorePkid(Integer storePkid) {
		this.storePkid = storePkid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_info.BRIEF_INTRODUCTION
	 * @return  the value of goods_info.BRIEF_INTRODUCTION
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getBriefIntroduction() {
		return briefIntroduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_info.BRIEF_INTRODUCTION
	 * @param briefIntroduction  the value for goods_info.BRIEF_INTRODUCTION
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setBriefIntroduction(String briefIntroduction) {
		this.briefIntroduction = briefIntroduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_info.EXPOSURE
	 * @return  the value of goods_info.EXPOSURE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getExposure() {
		return exposure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_info.EXPOSURE
	 * @param exposure  the value for goods_info.EXPOSURE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setExposure(Integer exposure) {
		this.exposure = exposure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_info.WEIGHTS
	 * @return  the value of goods_info.WEIGHTS
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getWeights() {
		return weights;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_info.WEIGHTS
	 * @param weights  the value for goods_info.WEIGHTS
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setWeights(Integer weights) {
		this.weights = weights;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_info.MAKE_EMP
	 * @return  the value of goods_info.MAKE_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getMakeEmp() {
		return makeEmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_info.MAKE_EMP
	 * @param makeEmp  the value for goods_info.MAKE_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setMakeEmp(Integer makeEmp) {
		this.makeEmp = makeEmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_info.MAKE_TIME
	 * @return  the value of goods_info.MAKE_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Date getMakeTime() {
		return makeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_info.MAKE_TIME
	 * @param makeTime  the value for goods_info.MAKE_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setMakeTime(Date makeTime) {
		this.makeTime = makeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_info.MODIFY_EMP
	 * @return  the value of goods_info.MODIFY_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getModifyEmp() {
		return modifyEmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_info.MODIFY_EMP
	 * @param modifyEmp  the value for goods_info.MODIFY_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setModifyEmp(Integer modifyEmp) {
		this.modifyEmp = modifyEmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_info.MODIFY_TIME
	 * @return  the value of goods_info.MODIFY_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_info.MODIFY_TIME
	 * @param modifyTime  the value for goods_info.MODIFY_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_info.VER
	 * @return  the value of goods_info.VER
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getVer() {
		return ver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_info.VER
	 * @param ver  the value for goods_info.VER
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setVer(Integer ver) {
		this.ver = ver;
	}
}