package com.catike_mall.domain.entity.normal;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GoodsInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table goods_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table goods_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table goods_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public GoodsInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table goods_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPkIdIsNull() {
			addCriterion("PK_ID is null");
			return (Criteria) this;
		}

		public Criteria andPkIdIsNotNull() {
			addCriterion("PK_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPkIdEqualTo(Integer value) {
			addCriterion("PK_ID =", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdNotEqualTo(Integer value) {
			addCriterion("PK_ID <>", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdGreaterThan(Integer value) {
			addCriterion("PK_ID >", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("PK_ID >=", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdLessThan(Integer value) {
			addCriterion("PK_ID <", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdLessThanOrEqualTo(Integer value) {
			addCriterion("PK_ID <=", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdIn(List<Integer> values) {
			addCriterion("PK_ID in", values, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdNotIn(List<Integer> values) {
			addCriterion("PK_ID not in", values, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdBetween(Integer value1, Integer value2) {
			addCriterion("PK_ID between", value1, value2, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdNotBetween(Integer value1, Integer value2) {
			addCriterion("PK_ID not between", value1, value2, "pkId");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("NAME is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("NAME is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("NAME =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("NAME <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("NAME >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("NAME >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("NAME <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("NAME <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("NAME like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("NAME not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("NAME in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("NAME not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("NAME between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("NAME not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andEnableIsNull() {
			addCriterion("ENABLE is null");
			return (Criteria) this;
		}

		public Criteria andEnableIsNotNull() {
			addCriterion("ENABLE is not null");
			return (Criteria) this;
		}

		public Criteria andEnableEqualTo(Boolean value) {
			addCriterion("ENABLE =", value, "enable");
			return (Criteria) this;
		}

		public Criteria andEnableNotEqualTo(Boolean value) {
			addCriterion("ENABLE <>", value, "enable");
			return (Criteria) this;
		}

		public Criteria andEnableGreaterThan(Boolean value) {
			addCriterion("ENABLE >", value, "enable");
			return (Criteria) this;
		}

		public Criteria andEnableGreaterThanOrEqualTo(Boolean value) {
			addCriterion("ENABLE >=", value, "enable");
			return (Criteria) this;
		}

		public Criteria andEnableLessThan(Boolean value) {
			addCriterion("ENABLE <", value, "enable");
			return (Criteria) this;
		}

		public Criteria andEnableLessThanOrEqualTo(Boolean value) {
			addCriterion("ENABLE <=", value, "enable");
			return (Criteria) this;
		}

		public Criteria andEnableIn(List<Boolean> values) {
			addCriterion("ENABLE in", values, "enable");
			return (Criteria) this;
		}

		public Criteria andEnableNotIn(List<Boolean> values) {
			addCriterion("ENABLE not in", values, "enable");
			return (Criteria) this;
		}

		public Criteria andEnableBetween(Boolean value1, Boolean value2) {
			addCriterion("ENABLE between", value1, value2, "enable");
			return (Criteria) this;
		}

		public Criteria andEnableNotBetween(Boolean value1, Boolean value2) {
			addCriterion("ENABLE not between", value1, value2, "enable");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("PRICE is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("PRICE is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Long value) {
			addCriterion("PRICE =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Long value) {
			addCriterion("PRICE <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Long value) {
			addCriterion("PRICE >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Long value) {
			addCriterion("PRICE >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Long value) {
			addCriterion("PRICE <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Long value) {
			addCriterion("PRICE <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Long> values) {
			addCriterion("PRICE in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Long> values) {
			addCriterion("PRICE not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Long value1, Long value2) {
			addCriterion("PRICE between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Long value1, Long value2) {
			addCriterion("PRICE not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andCountIsNull() {
			addCriterion("COUNT is null");
			return (Criteria) this;
		}

		public Criteria andCountIsNotNull() {
			addCriterion("COUNT is not null");
			return (Criteria) this;
		}

		public Criteria andCountEqualTo(Integer value) {
			addCriterion("COUNT =", value, "count");
			return (Criteria) this;
		}

		public Criteria andCountNotEqualTo(Integer value) {
			addCriterion("COUNT <>", value, "count");
			return (Criteria) this;
		}

		public Criteria andCountGreaterThan(Integer value) {
			addCriterion("COUNT >", value, "count");
			return (Criteria) this;
		}

		public Criteria andCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("COUNT >=", value, "count");
			return (Criteria) this;
		}

		public Criteria andCountLessThan(Integer value) {
			addCriterion("COUNT <", value, "count");
			return (Criteria) this;
		}

		public Criteria andCountLessThanOrEqualTo(Integer value) {
			addCriterion("COUNT <=", value, "count");
			return (Criteria) this;
		}

		public Criteria andCountIn(List<Integer> values) {
			addCriterion("COUNT in", values, "count");
			return (Criteria) this;
		}

		public Criteria andCountNotIn(List<Integer> values) {
			addCriterion("COUNT not in", values, "count");
			return (Criteria) this;
		}

		public Criteria andCountBetween(Integer value1, Integer value2) {
			addCriterion("COUNT between", value1, value2, "count");
			return (Criteria) this;
		}

		public Criteria andCountNotBetween(Integer value1, Integer value2) {
			addCriterion("COUNT not between", value1, value2, "count");
			return (Criteria) this;
		}

		public Criteria andImageDirIsNull() {
			addCriterion("IMAGE_DIR is null");
			return (Criteria) this;
		}

		public Criteria andImageDirIsNotNull() {
			addCriterion("IMAGE_DIR is not null");
			return (Criteria) this;
		}

		public Criteria andImageDirEqualTo(String value) {
			addCriterion("IMAGE_DIR =", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirNotEqualTo(String value) {
			addCriterion("IMAGE_DIR <>", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirGreaterThan(String value) {
			addCriterion("IMAGE_DIR >", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirGreaterThanOrEqualTo(String value) {
			addCriterion("IMAGE_DIR >=", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirLessThan(String value) {
			addCriterion("IMAGE_DIR <", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirLessThanOrEqualTo(String value) {
			addCriterion("IMAGE_DIR <=", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirLike(String value) {
			addCriterion("IMAGE_DIR like", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirNotLike(String value) {
			addCriterion("IMAGE_DIR not like", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirIn(List<String> values) {
			addCriterion("IMAGE_DIR in", values, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirNotIn(List<String> values) {
			addCriterion("IMAGE_DIR not in", values, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirBetween(String value1, String value2) {
			addCriterion("IMAGE_DIR between", value1, value2, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirNotBetween(String value1, String value2) {
			addCriterion("IMAGE_DIR not between", value1, value2, "imageDir");
			return (Criteria) this;
		}

		public Criteria andStorePkidIsNull() {
			addCriterion("STORE_PKID is null");
			return (Criteria) this;
		}

		public Criteria andStorePkidIsNotNull() {
			addCriterion("STORE_PKID is not null");
			return (Criteria) this;
		}

		public Criteria andStorePkidEqualTo(Integer value) {
			addCriterion("STORE_PKID =", value, "storePkid");
			return (Criteria) this;
		}

		public Criteria andStorePkidNotEqualTo(Integer value) {
			addCriterion("STORE_PKID <>", value, "storePkid");
			return (Criteria) this;
		}

		public Criteria andStorePkidGreaterThan(Integer value) {
			addCriterion("STORE_PKID >", value, "storePkid");
			return (Criteria) this;
		}

		public Criteria andStorePkidGreaterThanOrEqualTo(Integer value) {
			addCriterion("STORE_PKID >=", value, "storePkid");
			return (Criteria) this;
		}

		public Criteria andStorePkidLessThan(Integer value) {
			addCriterion("STORE_PKID <", value, "storePkid");
			return (Criteria) this;
		}

		public Criteria andStorePkidLessThanOrEqualTo(Integer value) {
			addCriterion("STORE_PKID <=", value, "storePkid");
			return (Criteria) this;
		}

		public Criteria andStorePkidIn(List<Integer> values) {
			addCriterion("STORE_PKID in", values, "storePkid");
			return (Criteria) this;
		}

		public Criteria andStorePkidNotIn(List<Integer> values) {
			addCriterion("STORE_PKID not in", values, "storePkid");
			return (Criteria) this;
		}

		public Criteria andStorePkidBetween(Integer value1, Integer value2) {
			addCriterion("STORE_PKID between", value1, value2, "storePkid");
			return (Criteria) this;
		}

		public Criteria andStorePkidNotBetween(Integer value1, Integer value2) {
			addCriterion("STORE_PKID not between", value1, value2, "storePkid");
			return (Criteria) this;
		}

		public Criteria andBriefIntroductionIsNull() {
			addCriterion("BRIEF_INTRODUCTION is null");
			return (Criteria) this;
		}

		public Criteria andBriefIntroductionIsNotNull() {
			addCriterion("BRIEF_INTRODUCTION is not null");
			return (Criteria) this;
		}

		public Criteria andBriefIntroductionEqualTo(String value) {
			addCriterion("BRIEF_INTRODUCTION =", value, "briefIntroduction");
			return (Criteria) this;
		}

		public Criteria andBriefIntroductionNotEqualTo(String value) {
			addCriterion("BRIEF_INTRODUCTION <>", value, "briefIntroduction");
			return (Criteria) this;
		}

		public Criteria andBriefIntroductionGreaterThan(String value) {
			addCriterion("BRIEF_INTRODUCTION >", value, "briefIntroduction");
			return (Criteria) this;
		}

		public Criteria andBriefIntroductionGreaterThanOrEqualTo(String value) {
			addCriterion("BRIEF_INTRODUCTION >=", value, "briefIntroduction");
			return (Criteria) this;
		}

		public Criteria andBriefIntroductionLessThan(String value) {
			addCriterion("BRIEF_INTRODUCTION <", value, "briefIntroduction");
			return (Criteria) this;
		}

		public Criteria andBriefIntroductionLessThanOrEqualTo(String value) {
			addCriterion("BRIEF_INTRODUCTION <=", value, "briefIntroduction");
			return (Criteria) this;
		}

		public Criteria andBriefIntroductionLike(String value) {
			addCriterion("BRIEF_INTRODUCTION like", value, "briefIntroduction");
			return (Criteria) this;
		}

		public Criteria andBriefIntroductionNotLike(String value) {
			addCriterion("BRIEF_INTRODUCTION not like", value, "briefIntroduction");
			return (Criteria) this;
		}

		public Criteria andBriefIntroductionIn(List<String> values) {
			addCriterion("BRIEF_INTRODUCTION in", values, "briefIntroduction");
			return (Criteria) this;
		}

		public Criteria andBriefIntroductionNotIn(List<String> values) {
			addCriterion("BRIEF_INTRODUCTION not in", values, "briefIntroduction");
			return (Criteria) this;
		}

		public Criteria andBriefIntroductionBetween(String value1, String value2) {
			addCriterion("BRIEF_INTRODUCTION between", value1, value2, "briefIntroduction");
			return (Criteria) this;
		}

		public Criteria andBriefIntroductionNotBetween(String value1, String value2) {
			addCriterion("BRIEF_INTRODUCTION not between", value1, value2, "briefIntroduction");
			return (Criteria) this;
		}

		public Criteria andExposureIsNull() {
			addCriterion("EXPOSURE is null");
			return (Criteria) this;
		}

		public Criteria andExposureIsNotNull() {
			addCriterion("EXPOSURE is not null");
			return (Criteria) this;
		}

		public Criteria andExposureEqualTo(Integer value) {
			addCriterion("EXPOSURE =", value, "exposure");
			return (Criteria) this;
		}

		public Criteria andExposureNotEqualTo(Integer value) {
			addCriterion("EXPOSURE <>", value, "exposure");
			return (Criteria) this;
		}

		public Criteria andExposureGreaterThan(Integer value) {
			addCriterion("EXPOSURE >", value, "exposure");
			return (Criteria) this;
		}

		public Criteria andExposureGreaterThanOrEqualTo(Integer value) {
			addCriterion("EXPOSURE >=", value, "exposure");
			return (Criteria) this;
		}

		public Criteria andExposureLessThan(Integer value) {
			addCriterion("EXPOSURE <", value, "exposure");
			return (Criteria) this;
		}

		public Criteria andExposureLessThanOrEqualTo(Integer value) {
			addCriterion("EXPOSURE <=", value, "exposure");
			return (Criteria) this;
		}

		public Criteria andExposureIn(List<Integer> values) {
			addCriterion("EXPOSURE in", values, "exposure");
			return (Criteria) this;
		}

		public Criteria andExposureNotIn(List<Integer> values) {
			addCriterion("EXPOSURE not in", values, "exposure");
			return (Criteria) this;
		}

		public Criteria andExposureBetween(Integer value1, Integer value2) {
			addCriterion("EXPOSURE between", value1, value2, "exposure");
			return (Criteria) this;
		}

		public Criteria andExposureNotBetween(Integer value1, Integer value2) {
			addCriterion("EXPOSURE not between", value1, value2, "exposure");
			return (Criteria) this;
		}

		public Criteria andWeightsIsNull() {
			addCriterion("WEIGHTS is null");
			return (Criteria) this;
		}

		public Criteria andWeightsIsNotNull() {
			addCriterion("WEIGHTS is not null");
			return (Criteria) this;
		}

		public Criteria andWeightsEqualTo(Integer value) {
			addCriterion("WEIGHTS =", value, "weights");
			return (Criteria) this;
		}

		public Criteria andWeightsNotEqualTo(Integer value) {
			addCriterion("WEIGHTS <>", value, "weights");
			return (Criteria) this;
		}

		public Criteria andWeightsGreaterThan(Integer value) {
			addCriterion("WEIGHTS >", value, "weights");
			return (Criteria) this;
		}

		public Criteria andWeightsGreaterThanOrEqualTo(Integer value) {
			addCriterion("WEIGHTS >=", value, "weights");
			return (Criteria) this;
		}

		public Criteria andWeightsLessThan(Integer value) {
			addCriterion("WEIGHTS <", value, "weights");
			return (Criteria) this;
		}

		public Criteria andWeightsLessThanOrEqualTo(Integer value) {
			addCriterion("WEIGHTS <=", value, "weights");
			return (Criteria) this;
		}

		public Criteria andWeightsIn(List<Integer> values) {
			addCriterion("WEIGHTS in", values, "weights");
			return (Criteria) this;
		}

		public Criteria andWeightsNotIn(List<Integer> values) {
			addCriterion("WEIGHTS not in", values, "weights");
			return (Criteria) this;
		}

		public Criteria andWeightsBetween(Integer value1, Integer value2) {
			addCriterion("WEIGHTS between", value1, value2, "weights");
			return (Criteria) this;
		}

		public Criteria andWeightsNotBetween(Integer value1, Integer value2) {
			addCriterion("WEIGHTS not between", value1, value2, "weights");
			return (Criteria) this;
		}

		public Criteria andMakeEmpIsNull() {
			addCriterion("MAKE_EMP is null");
			return (Criteria) this;
		}

		public Criteria andMakeEmpIsNotNull() {
			addCriterion("MAKE_EMP is not null");
			return (Criteria) this;
		}

		public Criteria andMakeEmpEqualTo(Integer value) {
			addCriterion("MAKE_EMP =", value, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpNotEqualTo(Integer value) {
			addCriterion("MAKE_EMP <>", value, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpGreaterThan(Integer value) {
			addCriterion("MAKE_EMP >", value, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpGreaterThanOrEqualTo(Integer value) {
			addCriterion("MAKE_EMP >=", value, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpLessThan(Integer value) {
			addCriterion("MAKE_EMP <", value, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpLessThanOrEqualTo(Integer value) {
			addCriterion("MAKE_EMP <=", value, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpIn(List<Integer> values) {
			addCriterion("MAKE_EMP in", values, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpNotIn(List<Integer> values) {
			addCriterion("MAKE_EMP not in", values, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpBetween(Integer value1, Integer value2) {
			addCriterion("MAKE_EMP between", value1, value2, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpNotBetween(Integer value1, Integer value2) {
			addCriterion("MAKE_EMP not between", value1, value2, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeTimeIsNull() {
			addCriterion("MAKE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andMakeTimeIsNotNull() {
			addCriterion("MAKE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andMakeTimeEqualTo(Date value) {
			addCriterion("MAKE_TIME =", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeNotEqualTo(Date value) {
			addCriterion("MAKE_TIME <>", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeGreaterThan(Date value) {
			addCriterion("MAKE_TIME >", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("MAKE_TIME >=", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeLessThan(Date value) {
			addCriterion("MAKE_TIME <", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeLessThanOrEqualTo(Date value) {
			addCriterion("MAKE_TIME <=", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeIn(List<Date> values) {
			addCriterion("MAKE_TIME in", values, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeNotIn(List<Date> values) {
			addCriterion("MAKE_TIME not in", values, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeBetween(Date value1, Date value2) {
			addCriterion("MAKE_TIME between", value1, value2, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeNotBetween(Date value1, Date value2) {
			addCriterion("MAKE_TIME not between", value1, value2, "makeTime");
			return (Criteria) this;
		}

		public Criteria andModifyEmpIsNull() {
			addCriterion("MODIFY_EMP is null");
			return (Criteria) this;
		}

		public Criteria andModifyEmpIsNotNull() {
			addCriterion("MODIFY_EMP is not null");
			return (Criteria) this;
		}

		public Criteria andModifyEmpEqualTo(Integer value) {
			addCriterion("MODIFY_EMP =", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpNotEqualTo(Integer value) {
			addCriterion("MODIFY_EMP <>", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpGreaterThan(Integer value) {
			addCriterion("MODIFY_EMP >", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpGreaterThanOrEqualTo(Integer value) {
			addCriterion("MODIFY_EMP >=", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpLessThan(Integer value) {
			addCriterion("MODIFY_EMP <", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpLessThanOrEqualTo(Integer value) {
			addCriterion("MODIFY_EMP <=", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpIn(List<Integer> values) {
			addCriterion("MODIFY_EMP in", values, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpNotIn(List<Integer> values) {
			addCriterion("MODIFY_EMP not in", values, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpBetween(Integer value1, Integer value2) {
			addCriterion("MODIFY_EMP between", value1, value2, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpNotBetween(Integer value1, Integer value2) {
			addCriterion("MODIFY_EMP not between", value1, value2, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("MODIFY_TIME is null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("MODIFY_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualTo(Date value) {
			addCriterion("MODIFY_TIME =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualTo(Date value) {
			addCriterion("MODIFY_TIME <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThan(Date value) {
			addCriterion("MODIFY_TIME >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("MODIFY_TIME >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThan(Date value) {
			addCriterion("MODIFY_TIME <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("MODIFY_TIME <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIn(List<Date> values) {
			addCriterion("MODIFY_TIME in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotIn(List<Date> values) {
			addCriterion("MODIFY_TIME not in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeBetween(Date value1, Date value2) {
			addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andVerIsNull() {
			addCriterion("VER is null");
			return (Criteria) this;
		}

		public Criteria andVerIsNotNull() {
			addCriterion("VER is not null");
			return (Criteria) this;
		}

		public Criteria andVerEqualTo(Integer value) {
			addCriterion("VER =", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotEqualTo(Integer value) {
			addCriterion("VER <>", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerGreaterThan(Integer value) {
			addCriterion("VER >", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerGreaterThanOrEqualTo(Integer value) {
			addCriterion("VER >=", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerLessThan(Integer value) {
			addCriterion("VER <", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerLessThanOrEqualTo(Integer value) {
			addCriterion("VER <=", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerIn(List<Integer> values) {
			addCriterion("VER in", values, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotIn(List<Integer> values) {
			addCriterion("VER not in", values, "ver");
			return (Criteria) this;
		}

		public Criteria andVerBetween(Integer value1, Integer value2) {
			addCriterion("VER between", value1, value2, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotBetween(Integer value1, Integer value2) {
			addCriterion("VER not between", value1, value2, "ver");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table goods_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_info
     *
     * @mbg.generated do_not_delete_during_merge Sun Jun 04 04:33:05 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}