package com.catike_mall.domain.entity.normal;

import java.util.Date;

public class GoodsDetailDis {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_detail_dis.PK_ID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer pkId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_detail_dis.GOODS_PK_ID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer goodsPkId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_detail_dis.DISCRIBE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String discribe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_detail_dis.MAKE_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer makeEmp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_detail_dis.MAKE_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Date makeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_detail_dis.MODIFY_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer modifyEmp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_detail_dis.MODIFY_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_detail_dis.VER
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer ver;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_detail_dis.PK_ID
	 * @return  the value of goods_detail_dis.PK_ID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getPkId() {
		return pkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_detail_dis.PK_ID
	 * @param pkId  the value for goods_detail_dis.PK_ID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setPkId(Integer pkId) {
		this.pkId = pkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_detail_dis.GOODS_PK_ID
	 * @return  the value of goods_detail_dis.GOODS_PK_ID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getGoodsPkId() {
		return goodsPkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_detail_dis.GOODS_PK_ID
	 * @param goodsPkId  the value for goods_detail_dis.GOODS_PK_ID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setGoodsPkId(Integer goodsPkId) {
		this.goodsPkId = goodsPkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_detail_dis.DISCRIBE
	 * @return  the value of goods_detail_dis.DISCRIBE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getDiscribe() {
		return discribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_detail_dis.DISCRIBE
	 * @param discribe  the value for goods_detail_dis.DISCRIBE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setDiscribe(String discribe) {
		this.discribe = discribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_detail_dis.MAKE_EMP
	 * @return  the value of goods_detail_dis.MAKE_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getMakeEmp() {
		return makeEmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_detail_dis.MAKE_EMP
	 * @param makeEmp  the value for goods_detail_dis.MAKE_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setMakeEmp(Integer makeEmp) {
		this.makeEmp = makeEmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_detail_dis.MAKE_TIME
	 * @return  the value of goods_detail_dis.MAKE_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Date getMakeTime() {
		return makeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_detail_dis.MAKE_TIME
	 * @param makeTime  the value for goods_detail_dis.MAKE_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setMakeTime(Date makeTime) {
		this.makeTime = makeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_detail_dis.MODIFY_EMP
	 * @return  the value of goods_detail_dis.MODIFY_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getModifyEmp() {
		return modifyEmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_detail_dis.MODIFY_EMP
	 * @param modifyEmp  the value for goods_detail_dis.MODIFY_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setModifyEmp(Integer modifyEmp) {
		this.modifyEmp = modifyEmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_detail_dis.MODIFY_TIME
	 * @return  the value of goods_detail_dis.MODIFY_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_detail_dis.MODIFY_TIME
	 * @param modifyTime  the value for goods_detail_dis.MODIFY_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_detail_dis.VER
	 * @return  the value of goods_detail_dis.VER
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getVer() {
		return ver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_detail_dis.VER
	 * @param ver  the value for goods_detail_dis.VER
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setVer(Integer ver) {
		this.ver = ver;
	}
}