package com.catike_mall.domain.entity.normal;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InnerMailExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public InnerMailExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPkIdIsNull() {
			addCriterion("PK_ID is null");
			return (Criteria) this;
		}

		public Criteria andPkIdIsNotNull() {
			addCriterion("PK_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPkIdEqualTo(Integer value) {
			addCriterion("PK_ID =", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdNotEqualTo(Integer value) {
			addCriterion("PK_ID <>", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdGreaterThan(Integer value) {
			addCriterion("PK_ID >", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("PK_ID >=", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdLessThan(Integer value) {
			addCriterion("PK_ID <", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdLessThanOrEqualTo(Integer value) {
			addCriterion("PK_ID <=", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdIn(List<Integer> values) {
			addCriterion("PK_ID in", values, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdNotIn(List<Integer> values) {
			addCriterion("PK_ID not in", values, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdBetween(Integer value1, Integer value2) {
			addCriterion("PK_ID between", value1, value2, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdNotBetween(Integer value1, Integer value2) {
			addCriterion("PK_ID not between", value1, value2, "pkId");
			return (Criteria) this;
		}

		public Criteria andFromIsNull() {
			addCriterion("FROM is null");
			return (Criteria) this;
		}

		public Criteria andFromIsNotNull() {
			addCriterion("FROM is not null");
			return (Criteria) this;
		}

		public Criteria andFromEqualTo(Integer value) {
			addCriterion("FROM =", value, "from");
			return (Criteria) this;
		}

		public Criteria andFromNotEqualTo(Integer value) {
			addCriterion("FROM <>", value, "from");
			return (Criteria) this;
		}

		public Criteria andFromGreaterThan(Integer value) {
			addCriterion("FROM >", value, "from");
			return (Criteria) this;
		}

		public Criteria andFromGreaterThanOrEqualTo(Integer value) {
			addCriterion("FROM >=", value, "from");
			return (Criteria) this;
		}

		public Criteria andFromLessThan(Integer value) {
			addCriterion("FROM <", value, "from");
			return (Criteria) this;
		}

		public Criteria andFromLessThanOrEqualTo(Integer value) {
			addCriterion("FROM <=", value, "from");
			return (Criteria) this;
		}

		public Criteria andFromIn(List<Integer> values) {
			addCriterion("FROM in", values, "from");
			return (Criteria) this;
		}

		public Criteria andFromNotIn(List<Integer> values) {
			addCriterion("FROM not in", values, "from");
			return (Criteria) this;
		}

		public Criteria andFromBetween(Integer value1, Integer value2) {
			addCriterion("FROM between", value1, value2, "from");
			return (Criteria) this;
		}

		public Criteria andFromNotBetween(Integer value1, Integer value2) {
			addCriterion("FROM not between", value1, value2, "from");
			return (Criteria) this;
		}

		public Criteria andToIsNull() {
			addCriterion("TO is null");
			return (Criteria) this;
		}

		public Criteria andToIsNotNull() {
			addCriterion("TO is not null");
			return (Criteria) this;
		}

		public Criteria andToEqualTo(Integer value) {
			addCriterion("TO =", value, "to");
			return (Criteria) this;
		}

		public Criteria andToNotEqualTo(Integer value) {
			addCriterion("TO <>", value, "to");
			return (Criteria) this;
		}

		public Criteria andToGreaterThan(Integer value) {
			addCriterion("TO >", value, "to");
			return (Criteria) this;
		}

		public Criteria andToGreaterThanOrEqualTo(Integer value) {
			addCriterion("TO >=", value, "to");
			return (Criteria) this;
		}

		public Criteria andToLessThan(Integer value) {
			addCriterion("TO <", value, "to");
			return (Criteria) this;
		}

		public Criteria andToLessThanOrEqualTo(Integer value) {
			addCriterion("TO <=", value, "to");
			return (Criteria) this;
		}

		public Criteria andToIn(List<Integer> values) {
			addCriterion("TO in", values, "to");
			return (Criteria) this;
		}

		public Criteria andToNotIn(List<Integer> values) {
			addCriterion("TO not in", values, "to");
			return (Criteria) this;
		}

		public Criteria andToBetween(Integer value1, Integer value2) {
			addCriterion("TO between", value1, value2, "to");
			return (Criteria) this;
		}

		public Criteria andToNotBetween(Integer value1, Integer value2) {
			addCriterion("TO not between", value1, value2, "to");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("CONTENT is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("CONTENT is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("CONTENT =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("CONTENT <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("CONTENT >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("CONTENT >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("CONTENT <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("CONTENT <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("CONTENT like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("CONTENT not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("CONTENT in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("CONTENT not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("CONTENT between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("CONTENT not between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andUnreadIsNull() {
			addCriterion("UNREAD is null");
			return (Criteria) this;
		}

		public Criteria andUnreadIsNotNull() {
			addCriterion("UNREAD is not null");
			return (Criteria) this;
		}

		public Criteria andUnreadEqualTo(Boolean value) {
			addCriterion("UNREAD =", value, "unread");
			return (Criteria) this;
		}

		public Criteria andUnreadNotEqualTo(Boolean value) {
			addCriterion("UNREAD <>", value, "unread");
			return (Criteria) this;
		}

		public Criteria andUnreadGreaterThan(Boolean value) {
			addCriterion("UNREAD >", value, "unread");
			return (Criteria) this;
		}

		public Criteria andUnreadGreaterThanOrEqualTo(Boolean value) {
			addCriterion("UNREAD >=", value, "unread");
			return (Criteria) this;
		}

		public Criteria andUnreadLessThan(Boolean value) {
			addCriterion("UNREAD <", value, "unread");
			return (Criteria) this;
		}

		public Criteria andUnreadLessThanOrEqualTo(Boolean value) {
			addCriterion("UNREAD <=", value, "unread");
			return (Criteria) this;
		}

		public Criteria andUnreadIn(List<Boolean> values) {
			addCriterion("UNREAD in", values, "unread");
			return (Criteria) this;
		}

		public Criteria andUnreadNotIn(List<Boolean> values) {
			addCriterion("UNREAD not in", values, "unread");
			return (Criteria) this;
		}

		public Criteria andUnreadBetween(Boolean value1, Boolean value2) {
			addCriterion("UNREAD between", value1, value2, "unread");
			return (Criteria) this;
		}

		public Criteria andUnreadNotBetween(Boolean value1, Boolean value2) {
			addCriterion("UNREAD not between", value1, value2, "unread");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andMakeEmpIsNull() {
			addCriterion("MAKE_EMP is null");
			return (Criteria) this;
		}

		public Criteria andMakeEmpIsNotNull() {
			addCriterion("MAKE_EMP is not null");
			return (Criteria) this;
		}

		public Criteria andMakeEmpEqualTo(Integer value) {
			addCriterion("MAKE_EMP =", value, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpNotEqualTo(Integer value) {
			addCriterion("MAKE_EMP <>", value, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpGreaterThan(Integer value) {
			addCriterion("MAKE_EMP >", value, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpGreaterThanOrEqualTo(Integer value) {
			addCriterion("MAKE_EMP >=", value, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpLessThan(Integer value) {
			addCriterion("MAKE_EMP <", value, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpLessThanOrEqualTo(Integer value) {
			addCriterion("MAKE_EMP <=", value, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpIn(List<Integer> values) {
			addCriterion("MAKE_EMP in", values, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpNotIn(List<Integer> values) {
			addCriterion("MAKE_EMP not in", values, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpBetween(Integer value1, Integer value2) {
			addCriterion("MAKE_EMP between", value1, value2, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpNotBetween(Integer value1, Integer value2) {
			addCriterion("MAKE_EMP not between", value1, value2, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeTimeIsNull() {
			addCriterion("MAKE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andMakeTimeIsNotNull() {
			addCriterion("MAKE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andMakeTimeEqualTo(Date value) {
			addCriterion("MAKE_TIME =", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeNotEqualTo(Date value) {
			addCriterion("MAKE_TIME <>", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeGreaterThan(Date value) {
			addCriterion("MAKE_TIME >", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("MAKE_TIME >=", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeLessThan(Date value) {
			addCriterion("MAKE_TIME <", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeLessThanOrEqualTo(Date value) {
			addCriterion("MAKE_TIME <=", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeIn(List<Date> values) {
			addCriterion("MAKE_TIME in", values, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeNotIn(List<Date> values) {
			addCriterion("MAKE_TIME not in", values, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeBetween(Date value1, Date value2) {
			addCriterion("MAKE_TIME between", value1, value2, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeNotBetween(Date value1, Date value2) {
			addCriterion("MAKE_TIME not between", value1, value2, "makeTime");
			return (Criteria) this;
		}

		public Criteria andModifyEmpIsNull() {
			addCriterion("MODIFY_EMP is null");
			return (Criteria) this;
		}

		public Criteria andModifyEmpIsNotNull() {
			addCriterion("MODIFY_EMP is not null");
			return (Criteria) this;
		}

		public Criteria andModifyEmpEqualTo(Integer value) {
			addCriterion("MODIFY_EMP =", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpNotEqualTo(Integer value) {
			addCriterion("MODIFY_EMP <>", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpGreaterThan(Integer value) {
			addCriterion("MODIFY_EMP >", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpGreaterThanOrEqualTo(Integer value) {
			addCriterion("MODIFY_EMP >=", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpLessThan(Integer value) {
			addCriterion("MODIFY_EMP <", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpLessThanOrEqualTo(Integer value) {
			addCriterion("MODIFY_EMP <=", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpIn(List<Integer> values) {
			addCriterion("MODIFY_EMP in", values, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpNotIn(List<Integer> values) {
			addCriterion("MODIFY_EMP not in", values, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpBetween(Integer value1, Integer value2) {
			addCriterion("MODIFY_EMP between", value1, value2, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpNotBetween(Integer value1, Integer value2) {
			addCriterion("MODIFY_EMP not between", value1, value2, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("MODIFY_TIME is null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("MODIFY_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualTo(Date value) {
			addCriterion("MODIFY_TIME =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualTo(Date value) {
			addCriterion("MODIFY_TIME <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThan(Date value) {
			addCriterion("MODIFY_TIME >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("MODIFY_TIME >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThan(Date value) {
			addCriterion("MODIFY_TIME <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("MODIFY_TIME <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIn(List<Date> values) {
			addCriterion("MODIFY_TIME in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotIn(List<Date> values) {
			addCriterion("MODIFY_TIME not in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeBetween(Date value1, Date value2) {
			addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andVerIsNull() {
			addCriterion("VER is null");
			return (Criteria) this;
		}

		public Criteria andVerIsNotNull() {
			addCriterion("VER is not null");
			return (Criteria) this;
		}

		public Criteria andVerEqualTo(Integer value) {
			addCriterion("VER =", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotEqualTo(Integer value) {
			addCriterion("VER <>", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerGreaterThan(Integer value) {
			addCriterion("VER >", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerGreaterThanOrEqualTo(Integer value) {
			addCriterion("VER >=", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerLessThan(Integer value) {
			addCriterion("VER <", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerLessThanOrEqualTo(Integer value) {
			addCriterion("VER <=", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerIn(List<Integer> values) {
			addCriterion("VER in", values, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotIn(List<Integer> values) {
			addCriterion("VER not in", values, "ver");
			return (Criteria) this;
		}

		public Criteria andVerBetween(Integer value1, Integer value2) {
			addCriterion("VER between", value1, value2, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotBetween(Integer value1, Integer value2) {
			addCriterion("VER not between", value1, value2, "ver");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inner_mail
     *
     * @mbg.generated do_not_delete_during_merge Sat Aug 26 12:48:33 EET 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}