package com.catike_mall.domain.entity.normal;

import java.math.BigDecimal;
import java.util.Date;

public class OrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.PK_ID
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    private Integer pkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.ORDER_NUM
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    private String orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.GOODS_PKID
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    private Integer goodsPkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.BUYYER_PKID
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    private Integer buyyerPkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.QUANTITY
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.TOTAL_PRICE
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.STATUS
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.REMARKS
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.DELIVER_COM
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    private Integer deliverCom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.MAKE_EMP
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    private Integer makeEmp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.MAKE_TIME
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    private Date makeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.MODIFY_EMP
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    private Integer modifyEmp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.MODIFY_TIME
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.VER
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    private Integer ver;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.PK_ID
     *
     * @return the value of order_info.PK_ID
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public Integer getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.PK_ID
     *
     * @param pkId the value for order_info.PK_ID
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public void setPkId(Integer pkId) {
        this.pkId = pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.ORDER_NUM
     *
     * @return the value of order_info.ORDER_NUM
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.ORDER_NUM
     *
     * @param orderNum the value for order_info.ORDER_NUM
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.GOODS_PKID
     *
     * @return the value of order_info.GOODS_PKID
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public Integer getGoodsPkid() {
        return goodsPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.GOODS_PKID
     *
     * @param goodsPkid the value for order_info.GOODS_PKID
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public void setGoodsPkid(Integer goodsPkid) {
        this.goodsPkid = goodsPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.BUYYER_PKID
     *
     * @return the value of order_info.BUYYER_PKID
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public Integer getBuyyerPkid() {
        return buyyerPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.BUYYER_PKID
     *
     * @param buyyerPkid the value for order_info.BUYYER_PKID
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public void setBuyyerPkid(Integer buyyerPkid) {
        this.buyyerPkid = buyyerPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.QUANTITY
     *
     * @return the value of order_info.QUANTITY
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.QUANTITY
     *
     * @param quantity the value for order_info.QUANTITY
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.TOTAL_PRICE
     *
     * @return the value of order_info.TOTAL_PRICE
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.TOTAL_PRICE
     *
     * @param totalPrice the value for order_info.TOTAL_PRICE
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.STATUS
     *
     * @return the value of order_info.STATUS
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.STATUS
     *
     * @param status the value for order_info.STATUS
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.REMARKS
     *
     * @return the value of order_info.REMARKS
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.REMARKS
     *
     * @param remarks the value for order_info.REMARKS
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.DELIVER_COM
     *
     * @return the value of order_info.DELIVER_COM
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public Integer getDeliverCom() {
        return deliverCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.DELIVER_COM
     *
     * @param deliverCom the value for order_info.DELIVER_COM
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public void setDeliverCom(Integer deliverCom) {
        this.deliverCom = deliverCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.MAKE_EMP
     *
     * @return the value of order_info.MAKE_EMP
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public Integer getMakeEmp() {
        return makeEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.MAKE_EMP
     *
     * @param makeEmp the value for order_info.MAKE_EMP
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public void setMakeEmp(Integer makeEmp) {
        this.makeEmp = makeEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.MAKE_TIME
     *
     * @return the value of order_info.MAKE_TIME
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public Date getMakeTime() {
        return makeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.MAKE_TIME
     *
     * @param makeTime the value for order_info.MAKE_TIME
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public void setMakeTime(Date makeTime) {
        this.makeTime = makeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.MODIFY_EMP
     *
     * @return the value of order_info.MODIFY_EMP
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public Integer getModifyEmp() {
        return modifyEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.MODIFY_EMP
     *
     * @param modifyEmp the value for order_info.MODIFY_EMP
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public void setModifyEmp(Integer modifyEmp) {
        this.modifyEmp = modifyEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.MODIFY_TIME
     *
     * @return the value of order_info.MODIFY_TIME
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.MODIFY_TIME
     *
     * @param modifyTime the value for order_info.MODIFY_TIME
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.VER
     *
     * @return the value of order_info.VER
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public Integer getVer() {
        return ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.VER
     *
     * @param ver the value for order_info.VER
     *
     * @mbg.generated Sat Aug 26 17:34:55 EET 2017
     */
    public void setVer(Integer ver) {
        this.ver = ver;
    }
}