package com.catike_mall.domain.entity.normal;

import java.util.Date;

public class StoreInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column store_info.PK_ID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer pkId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column store_info.STORE_NAME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String storeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column store_info.OWNER_PKID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer ownerPkid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column store_info.IMAGE_DIR
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String imageDir;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column store_info.ADDRESS
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column store_info.DISCRIPTION
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String discription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column store_info.MAKE_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer makeEmp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column store_info.MAKE_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Date makeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column store_info.MODIFY_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer modifyEmp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column store_info.MODIFY_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column store_info.VER
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer ver;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column store_info.PK_ID
	 * @return  the value of store_info.PK_ID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getPkId() {
		return pkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column store_info.PK_ID
	 * @param pkId  the value for store_info.PK_ID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setPkId(Integer pkId) {
		this.pkId = pkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column store_info.STORE_NAME
	 * @return  the value of store_info.STORE_NAME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getStoreName() {
		return storeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column store_info.STORE_NAME
	 * @param storeName  the value for store_info.STORE_NAME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column store_info.OWNER_PKID
	 * @return  the value of store_info.OWNER_PKID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getOwnerPkid() {
		return ownerPkid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column store_info.OWNER_PKID
	 * @param ownerPkid  the value for store_info.OWNER_PKID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setOwnerPkid(Integer ownerPkid) {
		this.ownerPkid = ownerPkid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column store_info.IMAGE_DIR
	 * @return  the value of store_info.IMAGE_DIR
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getImageDir() {
		return imageDir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column store_info.IMAGE_DIR
	 * @param imageDir  the value for store_info.IMAGE_DIR
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setImageDir(String imageDir) {
		this.imageDir = imageDir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column store_info.ADDRESS
	 * @return  the value of store_info.ADDRESS
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column store_info.ADDRESS
	 * @param address  the value for store_info.ADDRESS
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column store_info.DISCRIPTION
	 * @return  the value of store_info.DISCRIPTION
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getDiscription() {
		return discription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column store_info.DISCRIPTION
	 * @param discription  the value for store_info.DISCRIPTION
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setDiscription(String discription) {
		this.discription = discription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column store_info.MAKE_EMP
	 * @return  the value of store_info.MAKE_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getMakeEmp() {
		return makeEmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column store_info.MAKE_EMP
	 * @param makeEmp  the value for store_info.MAKE_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setMakeEmp(Integer makeEmp) {
		this.makeEmp = makeEmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column store_info.MAKE_TIME
	 * @return  the value of store_info.MAKE_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Date getMakeTime() {
		return makeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column store_info.MAKE_TIME
	 * @param makeTime  the value for store_info.MAKE_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setMakeTime(Date makeTime) {
		this.makeTime = makeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column store_info.MODIFY_EMP
	 * @return  the value of store_info.MODIFY_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getModifyEmp() {
		return modifyEmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column store_info.MODIFY_EMP
	 * @param modifyEmp  the value for store_info.MODIFY_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setModifyEmp(Integer modifyEmp) {
		this.modifyEmp = modifyEmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column store_info.MODIFY_TIME
	 * @return  the value of store_info.MODIFY_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column store_info.MODIFY_TIME
	 * @param modifyTime  the value for store_info.MODIFY_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column store_info.VER
	 * @return  the value of store_info.VER
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getVer() {
		return ver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column store_info.VER
	 * @param ver  the value for store_info.VER
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setVer(Integer ver) {
		this.ver = ver;
	}
}