package com.catike_mall.domain.entity.normal;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StoreInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public StoreInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPkIdIsNull() {
			addCriterion("PK_ID is null");
			return (Criteria) this;
		}

		public Criteria andPkIdIsNotNull() {
			addCriterion("PK_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPkIdEqualTo(Integer value) {
			addCriterion("PK_ID =", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdNotEqualTo(Integer value) {
			addCriterion("PK_ID <>", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdGreaterThan(Integer value) {
			addCriterion("PK_ID >", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("PK_ID >=", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdLessThan(Integer value) {
			addCriterion("PK_ID <", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdLessThanOrEqualTo(Integer value) {
			addCriterion("PK_ID <=", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdIn(List<Integer> values) {
			addCriterion("PK_ID in", values, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdNotIn(List<Integer> values) {
			addCriterion("PK_ID not in", values, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdBetween(Integer value1, Integer value2) {
			addCriterion("PK_ID between", value1, value2, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdNotBetween(Integer value1, Integer value2) {
			addCriterion("PK_ID not between", value1, value2, "pkId");
			return (Criteria) this;
		}

		public Criteria andStoreNameIsNull() {
			addCriterion("STORE_NAME is null");
			return (Criteria) this;
		}

		public Criteria andStoreNameIsNotNull() {
			addCriterion("STORE_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andStoreNameEqualTo(String value) {
			addCriterion("STORE_NAME =", value, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameNotEqualTo(String value) {
			addCriterion("STORE_NAME <>", value, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameGreaterThan(String value) {
			addCriterion("STORE_NAME >", value, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameGreaterThanOrEqualTo(String value) {
			addCriterion("STORE_NAME >=", value, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameLessThan(String value) {
			addCriterion("STORE_NAME <", value, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameLessThanOrEqualTo(String value) {
			addCriterion("STORE_NAME <=", value, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameLike(String value) {
			addCriterion("STORE_NAME like", value, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameNotLike(String value) {
			addCriterion("STORE_NAME not like", value, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameIn(List<String> values) {
			addCriterion("STORE_NAME in", values, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameNotIn(List<String> values) {
			addCriterion("STORE_NAME not in", values, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameBetween(String value1, String value2) {
			addCriterion("STORE_NAME between", value1, value2, "storeName");
			return (Criteria) this;
		}

		public Criteria andStoreNameNotBetween(String value1, String value2) {
			addCriterion("STORE_NAME not between", value1, value2, "storeName");
			return (Criteria) this;
		}

		public Criteria andOwnerPkidIsNull() {
			addCriterion("OWNER_PKID is null");
			return (Criteria) this;
		}

		public Criteria andOwnerPkidIsNotNull() {
			addCriterion("OWNER_PKID is not null");
			return (Criteria) this;
		}

		public Criteria andOwnerPkidEqualTo(Integer value) {
			addCriterion("OWNER_PKID =", value, "ownerPkid");
			return (Criteria) this;
		}

		public Criteria andOwnerPkidNotEqualTo(Integer value) {
			addCriterion("OWNER_PKID <>", value, "ownerPkid");
			return (Criteria) this;
		}

		public Criteria andOwnerPkidGreaterThan(Integer value) {
			addCriterion("OWNER_PKID >", value, "ownerPkid");
			return (Criteria) this;
		}

		public Criteria andOwnerPkidGreaterThanOrEqualTo(Integer value) {
			addCriterion("OWNER_PKID >=", value, "ownerPkid");
			return (Criteria) this;
		}

		public Criteria andOwnerPkidLessThan(Integer value) {
			addCriterion("OWNER_PKID <", value, "ownerPkid");
			return (Criteria) this;
		}

		public Criteria andOwnerPkidLessThanOrEqualTo(Integer value) {
			addCriterion("OWNER_PKID <=", value, "ownerPkid");
			return (Criteria) this;
		}

		public Criteria andOwnerPkidIn(List<Integer> values) {
			addCriterion("OWNER_PKID in", values, "ownerPkid");
			return (Criteria) this;
		}

		public Criteria andOwnerPkidNotIn(List<Integer> values) {
			addCriterion("OWNER_PKID not in", values, "ownerPkid");
			return (Criteria) this;
		}

		public Criteria andOwnerPkidBetween(Integer value1, Integer value2) {
			addCriterion("OWNER_PKID between", value1, value2, "ownerPkid");
			return (Criteria) this;
		}

		public Criteria andOwnerPkidNotBetween(Integer value1, Integer value2) {
			addCriterion("OWNER_PKID not between", value1, value2, "ownerPkid");
			return (Criteria) this;
		}

		public Criteria andImageDirIsNull() {
			addCriterion("IMAGE_DIR is null");
			return (Criteria) this;
		}

		public Criteria andImageDirIsNotNull() {
			addCriterion("IMAGE_DIR is not null");
			return (Criteria) this;
		}

		public Criteria andImageDirEqualTo(String value) {
			addCriterion("IMAGE_DIR =", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirNotEqualTo(String value) {
			addCriterion("IMAGE_DIR <>", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirGreaterThan(String value) {
			addCriterion("IMAGE_DIR >", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirGreaterThanOrEqualTo(String value) {
			addCriterion("IMAGE_DIR >=", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirLessThan(String value) {
			addCriterion("IMAGE_DIR <", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirLessThanOrEqualTo(String value) {
			addCriterion("IMAGE_DIR <=", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirLike(String value) {
			addCriterion("IMAGE_DIR like", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirNotLike(String value) {
			addCriterion("IMAGE_DIR not like", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirIn(List<String> values) {
			addCriterion("IMAGE_DIR in", values, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirNotIn(List<String> values) {
			addCriterion("IMAGE_DIR not in", values, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirBetween(String value1, String value2) {
			addCriterion("IMAGE_DIR between", value1, value2, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirNotBetween(String value1, String value2) {
			addCriterion("IMAGE_DIR not between", value1, value2, "imageDir");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("ADDRESS is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("ADDRESS is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("ADDRESS =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("ADDRESS <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("ADDRESS >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("ADDRESS >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("ADDRESS <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("ADDRESS <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("ADDRESS like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("ADDRESS not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("ADDRESS in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("ADDRESS not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("ADDRESS between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("ADDRESS not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andDiscriptionIsNull() {
			addCriterion("DISCRIPTION is null");
			return (Criteria) this;
		}

		public Criteria andDiscriptionIsNotNull() {
			addCriterion("DISCRIPTION is not null");
			return (Criteria) this;
		}

		public Criteria andDiscriptionEqualTo(String value) {
			addCriterion("DISCRIPTION =", value, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionNotEqualTo(String value) {
			addCriterion("DISCRIPTION <>", value, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionGreaterThan(String value) {
			addCriterion("DISCRIPTION >", value, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionGreaterThanOrEqualTo(String value) {
			addCriterion("DISCRIPTION >=", value, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionLessThan(String value) {
			addCriterion("DISCRIPTION <", value, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionLessThanOrEqualTo(String value) {
			addCriterion("DISCRIPTION <=", value, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionLike(String value) {
			addCriterion("DISCRIPTION like", value, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionNotLike(String value) {
			addCriterion("DISCRIPTION not like", value, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionIn(List<String> values) {
			addCriterion("DISCRIPTION in", values, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionNotIn(List<String> values) {
			addCriterion("DISCRIPTION not in", values, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionBetween(String value1, String value2) {
			addCriterion("DISCRIPTION between", value1, value2, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionNotBetween(String value1, String value2) {
			addCriterion("DISCRIPTION not between", value1, value2, "discription");
			return (Criteria) this;
		}

		public Criteria andMakeEmpIsNull() {
			addCriterion("MAKE_EMP is null");
			return (Criteria) this;
		}

		public Criteria andMakeEmpIsNotNull() {
			addCriterion("MAKE_EMP is not null");
			return (Criteria) this;
		}

		public Criteria andMakeEmpEqualTo(Integer value) {
			addCriterion("MAKE_EMP =", value, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpNotEqualTo(Integer value) {
			addCriterion("MAKE_EMP <>", value, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpGreaterThan(Integer value) {
			addCriterion("MAKE_EMP >", value, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpGreaterThanOrEqualTo(Integer value) {
			addCriterion("MAKE_EMP >=", value, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpLessThan(Integer value) {
			addCriterion("MAKE_EMP <", value, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpLessThanOrEqualTo(Integer value) {
			addCriterion("MAKE_EMP <=", value, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpIn(List<Integer> values) {
			addCriterion("MAKE_EMP in", values, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpNotIn(List<Integer> values) {
			addCriterion("MAKE_EMP not in", values, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpBetween(Integer value1, Integer value2) {
			addCriterion("MAKE_EMP between", value1, value2, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeEmpNotBetween(Integer value1, Integer value2) {
			addCriterion("MAKE_EMP not between", value1, value2, "makeEmp");
			return (Criteria) this;
		}

		public Criteria andMakeTimeIsNull() {
			addCriterion("MAKE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andMakeTimeIsNotNull() {
			addCriterion("MAKE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andMakeTimeEqualTo(Date value) {
			addCriterion("MAKE_TIME =", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeNotEqualTo(Date value) {
			addCriterion("MAKE_TIME <>", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeGreaterThan(Date value) {
			addCriterion("MAKE_TIME >", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("MAKE_TIME >=", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeLessThan(Date value) {
			addCriterion("MAKE_TIME <", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeLessThanOrEqualTo(Date value) {
			addCriterion("MAKE_TIME <=", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeIn(List<Date> values) {
			addCriterion("MAKE_TIME in", values, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeNotIn(List<Date> values) {
			addCriterion("MAKE_TIME not in", values, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeBetween(Date value1, Date value2) {
			addCriterion("MAKE_TIME between", value1, value2, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeNotBetween(Date value1, Date value2) {
			addCriterion("MAKE_TIME not between", value1, value2, "makeTime");
			return (Criteria) this;
		}

		public Criteria andModifyEmpIsNull() {
			addCriterion("MODIFY_EMP is null");
			return (Criteria) this;
		}

		public Criteria andModifyEmpIsNotNull() {
			addCriterion("MODIFY_EMP is not null");
			return (Criteria) this;
		}

		public Criteria andModifyEmpEqualTo(Integer value) {
			addCriterion("MODIFY_EMP =", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpNotEqualTo(Integer value) {
			addCriterion("MODIFY_EMP <>", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpGreaterThan(Integer value) {
			addCriterion("MODIFY_EMP >", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpGreaterThanOrEqualTo(Integer value) {
			addCriterion("MODIFY_EMP >=", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpLessThan(Integer value) {
			addCriterion("MODIFY_EMP <", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpLessThanOrEqualTo(Integer value) {
			addCriterion("MODIFY_EMP <=", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpIn(List<Integer> values) {
			addCriterion("MODIFY_EMP in", values, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpNotIn(List<Integer> values) {
			addCriterion("MODIFY_EMP not in", values, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpBetween(Integer value1, Integer value2) {
			addCriterion("MODIFY_EMP between", value1, value2, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpNotBetween(Integer value1, Integer value2) {
			addCriterion("MODIFY_EMP not between", value1, value2, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("MODIFY_TIME is null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("MODIFY_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualTo(Date value) {
			addCriterion("MODIFY_TIME =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualTo(Date value) {
			addCriterion("MODIFY_TIME <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThan(Date value) {
			addCriterion("MODIFY_TIME >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("MODIFY_TIME >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThan(Date value) {
			addCriterion("MODIFY_TIME <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("MODIFY_TIME <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIn(List<Date> values) {
			addCriterion("MODIFY_TIME in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotIn(List<Date> values) {
			addCriterion("MODIFY_TIME not in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeBetween(Date value1, Date value2) {
			addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andVerIsNull() {
			addCriterion("VER is null");
			return (Criteria) this;
		}

		public Criteria andVerIsNotNull() {
			addCriterion("VER is not null");
			return (Criteria) this;
		}

		public Criteria andVerEqualTo(Integer value) {
			addCriterion("VER =", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotEqualTo(Integer value) {
			addCriterion("VER <>", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerGreaterThan(Integer value) {
			addCriterion("VER >", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerGreaterThanOrEqualTo(Integer value) {
			addCriterion("VER >=", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerLessThan(Integer value) {
			addCriterion("VER <", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerLessThanOrEqualTo(Integer value) {
			addCriterion("VER <=", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerIn(List<Integer> values) {
			addCriterion("VER in", values, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotIn(List<Integer> values) {
			addCriterion("VER not in", values, "ver");
			return (Criteria) this;
		}

		public Criteria andVerBetween(Integer value1, Integer value2) {
			addCriterion("VER between", value1, value2, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotBetween(Integer value1, Integer value2) {
			addCriterion("VER not between", value1, value2, "ver");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table store_info
     *
     * @mbg.generated do_not_delete_during_merge Sun Jun 04 04:33:42 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}