package com.catike_mall.domain.entity.normal;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public UserInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPkIdIsNull() {
			addCriterion("PK_ID is null");
			return (Criteria) this;
		}

		public Criteria andPkIdIsNotNull() {
			addCriterion("PK_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPkIdEqualTo(Integer value) {
			addCriterion("PK_ID =", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdNotEqualTo(Integer value) {
			addCriterion("PK_ID <>", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdGreaterThan(Integer value) {
			addCriterion("PK_ID >", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("PK_ID >=", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdLessThan(Integer value) {
			addCriterion("PK_ID <", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdLessThanOrEqualTo(Integer value) {
			addCriterion("PK_ID <=", value, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdIn(List<Integer> values) {
			addCriterion("PK_ID in", values, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdNotIn(List<Integer> values) {
			addCriterion("PK_ID not in", values, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdBetween(Integer value1, Integer value2) {
			addCriterion("PK_ID between", value1, value2, "pkId");
			return (Criteria) this;
		}

		public Criteria andPkIdNotBetween(Integer value1, Integer value2) {
			addCriterion("PK_ID not between", value1, value2, "pkId");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("USERNAME is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("USERNAME is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("USERNAME =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("USERNAME <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("USERNAME >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("USERNAME >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("USERNAME <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("USERNAME <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("USERNAME like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("USERNAME not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("USERNAME in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("USERNAME not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("USERNAME between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("USERNAME not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("PASSWORD is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("PASSWORD is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("PASSWORD =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("PASSWORD <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("PASSWORD >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("PASSWORD >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("PASSWORD <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("PASSWORD <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("PASSWORD like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("PASSWORD not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("PASSWORD in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("PASSWORD not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("PASSWORD between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("PASSWORD not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andEnabledIsNull() {
			addCriterion("ENABLED is null");
			return (Criteria) this;
		}

		public Criteria andEnabledIsNotNull() {
			addCriterion("ENABLED is not null");
			return (Criteria) this;
		}

		public Criteria andEnabledEqualTo(Boolean value) {
			addCriterion("ENABLED =", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledNotEqualTo(Boolean value) {
			addCriterion("ENABLED <>", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledGreaterThan(Boolean value) {
			addCriterion("ENABLED >", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledGreaterThanOrEqualTo(Boolean value) {
			addCriterion("ENABLED >=", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledLessThan(Boolean value) {
			addCriterion("ENABLED <", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledLessThanOrEqualTo(Boolean value) {
			addCriterion("ENABLED <=", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledIn(List<Boolean> values) {
			addCriterion("ENABLED in", values, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledNotIn(List<Boolean> values) {
			addCriterion("ENABLED not in", values, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledBetween(Boolean value1, Boolean value2) {
			addCriterion("ENABLED between", value1, value2, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledNotBetween(Boolean value1, Boolean value2) {
			addCriterion("ENABLED not between", value1, value2, "enabled");
			return (Criteria) this;
		}

		public Criteria andAuthorityIsNull() {
			addCriterion("AUTHORITY is null");
			return (Criteria) this;
		}

		public Criteria andAuthorityIsNotNull() {
			addCriterion("AUTHORITY is not null");
			return (Criteria) this;
		}

		public Criteria andAuthorityEqualTo(String value) {
			addCriterion("AUTHORITY =", value, "authority");
			return (Criteria) this;
		}

		public Criteria andAuthorityNotEqualTo(String value) {
			addCriterion("AUTHORITY <>", value, "authority");
			return (Criteria) this;
		}

		public Criteria andAuthorityGreaterThan(String value) {
			addCriterion("AUTHORITY >", value, "authority");
			return (Criteria) this;
		}

		public Criteria andAuthorityGreaterThanOrEqualTo(String value) {
			addCriterion("AUTHORITY >=", value, "authority");
			return (Criteria) this;
		}

		public Criteria andAuthorityLessThan(String value) {
			addCriterion("AUTHORITY <", value, "authority");
			return (Criteria) this;
		}

		public Criteria andAuthorityLessThanOrEqualTo(String value) {
			addCriterion("AUTHORITY <=", value, "authority");
			return (Criteria) this;
		}

		public Criteria andAuthorityLike(String value) {
			addCriterion("AUTHORITY like", value, "authority");
			return (Criteria) this;
		}

		public Criteria andAuthorityNotLike(String value) {
			addCriterion("AUTHORITY not like", value, "authority");
			return (Criteria) this;
		}

		public Criteria andAuthorityIn(List<String> values) {
			addCriterion("AUTHORITY in", values, "authority");
			return (Criteria) this;
		}

		public Criteria andAuthorityNotIn(List<String> values) {
			addCriterion("AUTHORITY not in", values, "authority");
			return (Criteria) this;
		}

		public Criteria andAuthorityBetween(String value1, String value2) {
			addCriterion("AUTHORITY between", value1, value2, "authority");
			return (Criteria) this;
		}

		public Criteria andAuthorityNotBetween(String value1, String value2) {
			addCriterion("AUTHORITY not between", value1, value2, "authority");
			return (Criteria) this;
		}

		public Criteria andImageDirIsNull() {
			addCriterion("IMAGE_DIR is null");
			return (Criteria) this;
		}

		public Criteria andImageDirIsNotNull() {
			addCriterion("IMAGE_DIR is not null");
			return (Criteria) this;
		}

		public Criteria andImageDirEqualTo(String value) {
			addCriterion("IMAGE_DIR =", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirNotEqualTo(String value) {
			addCriterion("IMAGE_DIR <>", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirGreaterThan(String value) {
			addCriterion("IMAGE_DIR >", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirGreaterThanOrEqualTo(String value) {
			addCriterion("IMAGE_DIR >=", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirLessThan(String value) {
			addCriterion("IMAGE_DIR <", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirLessThanOrEqualTo(String value) {
			addCriterion("IMAGE_DIR <=", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirLike(String value) {
			addCriterion("IMAGE_DIR like", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirNotLike(String value) {
			addCriterion("IMAGE_DIR not like", value, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirIn(List<String> values) {
			addCriterion("IMAGE_DIR in", values, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirNotIn(List<String> values) {
			addCriterion("IMAGE_DIR not in", values, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirBetween(String value1, String value2) {
			addCriterion("IMAGE_DIR between", value1, value2, "imageDir");
			return (Criteria) this;
		}

		public Criteria andImageDirNotBetween(String value1, String value2) {
			addCriterion("IMAGE_DIR not between", value1, value2, "imageDir");
			return (Criteria) this;
		}

		public Criteria andFirstnameIsNull() {
			addCriterion("FIRSTNAME is null");
			return (Criteria) this;
		}

		public Criteria andFirstnameIsNotNull() {
			addCriterion("FIRSTNAME is not null");
			return (Criteria) this;
		}

		public Criteria andFirstnameEqualTo(String value) {
			addCriterion("FIRSTNAME =", value, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameNotEqualTo(String value) {
			addCriterion("FIRSTNAME <>", value, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameGreaterThan(String value) {
			addCriterion("FIRSTNAME >", value, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameGreaterThanOrEqualTo(String value) {
			addCriterion("FIRSTNAME >=", value, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameLessThan(String value) {
			addCriterion("FIRSTNAME <", value, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameLessThanOrEqualTo(String value) {
			addCriterion("FIRSTNAME <=", value, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameLike(String value) {
			addCriterion("FIRSTNAME like", value, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameNotLike(String value) {
			addCriterion("FIRSTNAME not like", value, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameIn(List<String> values) {
			addCriterion("FIRSTNAME in", values, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameNotIn(List<String> values) {
			addCriterion("FIRSTNAME not in", values, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameBetween(String value1, String value2) {
			addCriterion("FIRSTNAME between", value1, value2, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameNotBetween(String value1, String value2) {
			addCriterion("FIRSTNAME not between", value1, value2, "firstname");
			return (Criteria) this;
		}

		public Criteria andLastnameIsNull() {
			addCriterion("LASTNAME is null");
			return (Criteria) this;
		}

		public Criteria andLastnameIsNotNull() {
			addCriterion("LASTNAME is not null");
			return (Criteria) this;
		}

		public Criteria andLastnameEqualTo(String value) {
			addCriterion("LASTNAME =", value, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameNotEqualTo(String value) {
			addCriterion("LASTNAME <>", value, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameGreaterThan(String value) {
			addCriterion("LASTNAME >", value, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameGreaterThanOrEqualTo(String value) {
			addCriterion("LASTNAME >=", value, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameLessThan(String value) {
			addCriterion("LASTNAME <", value, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameLessThanOrEqualTo(String value) {
			addCriterion("LASTNAME <=", value, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameLike(String value) {
			addCriterion("LASTNAME like", value, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameNotLike(String value) {
			addCriterion("LASTNAME not like", value, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameIn(List<String> values) {
			addCriterion("LASTNAME in", values, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameNotIn(List<String> values) {
			addCriterion("LASTNAME not in", values, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameBetween(String value1, String value2) {
			addCriterion("LASTNAME between", value1, value2, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameNotBetween(String value1, String value2) {
			addCriterion("LASTNAME not between", value1, value2, "lastname");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("EMAIL is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("EMAIL is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("EMAIL =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("EMAIL <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("EMAIL >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("EMAIL >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("EMAIL <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("EMAIL <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("EMAIL like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("EMAIL not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("EMAIL in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("EMAIL not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("EMAIL between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("EMAIL not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andTelephoneIsNull() {
			addCriterion("TELEPHONE is null");
			return (Criteria) this;
		}

		public Criteria andTelephoneIsNotNull() {
			addCriterion("TELEPHONE is not null");
			return (Criteria) this;
		}

		public Criteria andTelephoneEqualTo(String value) {
			addCriterion("TELEPHONE =", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotEqualTo(String value) {
			addCriterion("TELEPHONE <>", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneGreaterThan(String value) {
			addCriterion("TELEPHONE >", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneGreaterThanOrEqualTo(String value) {
			addCriterion("TELEPHONE >=", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneLessThan(String value) {
			addCriterion("TELEPHONE <", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneLessThanOrEqualTo(String value) {
			addCriterion("TELEPHONE <=", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneLike(String value) {
			addCriterion("TELEPHONE like", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotLike(String value) {
			addCriterion("TELEPHONE not like", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneIn(List<String> values) {
			addCriterion("TELEPHONE in", values, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotIn(List<String> values) {
			addCriterion("TELEPHONE not in", values, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneBetween(String value1, String value2) {
			addCriterion("TELEPHONE between", value1, value2, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotBetween(String value1, String value2) {
			addCriterion("TELEPHONE not between", value1, value2, "telephone");
			return (Criteria) this;
		}

		public Criteria andFaxIsNull() {
			addCriterion("FAX is null");
			return (Criteria) this;
		}

		public Criteria andFaxIsNotNull() {
			addCriterion("FAX is not null");
			return (Criteria) this;
		}

		public Criteria andFaxEqualTo(String value) {
			addCriterion("FAX =", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotEqualTo(String value) {
			addCriterion("FAX <>", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxGreaterThan(String value) {
			addCriterion("FAX >", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxGreaterThanOrEqualTo(String value) {
			addCriterion("FAX >=", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxLessThan(String value) {
			addCriterion("FAX <", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxLessThanOrEqualTo(String value) {
			addCriterion("FAX <=", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxLike(String value) {
			addCriterion("FAX like", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotLike(String value) {
			addCriterion("FAX not like", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxIn(List<String> values) {
			addCriterion("FAX in", values, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotIn(List<String> values) {
			addCriterion("FAX not in", values, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxBetween(String value1, String value2) {
			addCriterion("FAX between", value1, value2, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotBetween(String value1, String value2) {
			addCriterion("FAX not between", value1, value2, "fax");
			return (Criteria) this;
		}

		public Criteria andCompanyIsNull() {
			addCriterion("COMPANY is null");
			return (Criteria) this;
		}

		public Criteria andCompanyIsNotNull() {
			addCriterion("COMPANY is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyEqualTo(String value) {
			addCriterion("COMPANY =", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyNotEqualTo(String value) {
			addCriterion("COMPANY <>", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyGreaterThan(String value) {
			addCriterion("COMPANY >", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyGreaterThanOrEqualTo(String value) {
			addCriterion("COMPANY >=", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyLessThan(String value) {
			addCriterion("COMPANY <", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyLessThanOrEqualTo(String value) {
			addCriterion("COMPANY <=", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyLike(String value) {
			addCriterion("COMPANY like", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyNotLike(String value) {
			addCriterion("COMPANY not like", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyIn(List<String> values) {
			addCriterion("COMPANY in", values, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyNotIn(List<String> values) {
			addCriterion("COMPANY not in", values, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyBetween(String value1, String value2) {
			addCriterion("COMPANY between", value1, value2, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyNotBetween(String value1, String value2) {
			addCriterion("COMPANY not between", value1, value2, "company");
			return (Criteria) this;
		}

		public Criteria andAddress1IsNull() {
			addCriterion("ADDRESS1 is null");
			return (Criteria) this;
		}

		public Criteria andAddress1IsNotNull() {
			addCriterion("ADDRESS1 is not null");
			return (Criteria) this;
		}

		public Criteria andAddress1EqualTo(String value) {
			addCriterion("ADDRESS1 =", value, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1NotEqualTo(String value) {
			addCriterion("ADDRESS1 <>", value, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1GreaterThan(String value) {
			addCriterion("ADDRESS1 >", value, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1GreaterThanOrEqualTo(String value) {
			addCriterion("ADDRESS1 >=", value, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1LessThan(String value) {
			addCriterion("ADDRESS1 <", value, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1LessThanOrEqualTo(String value) {
			addCriterion("ADDRESS1 <=", value, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1Like(String value) {
			addCriterion("ADDRESS1 like", value, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1NotLike(String value) {
			addCriterion("ADDRESS1 not like", value, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1In(List<String> values) {
			addCriterion("ADDRESS1 in", values, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1NotIn(List<String> values) {
			addCriterion("ADDRESS1 not in", values, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1Between(String value1, String value2) {
			addCriterion("ADDRESS1 between", value1, value2, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1NotBetween(String value1, String value2) {
			addCriterion("ADDRESS1 not between", value1, value2, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress2IsNull() {
			addCriterion("ADDRESS2 is null");
			return (Criteria) this;
		}

		public Criteria andAddress2IsNotNull() {
			addCriterion("ADDRESS2 is not null");
			return (Criteria) this;
		}

		public Criteria andAddress2EqualTo(String value) {
			addCriterion("ADDRESS2 =", value, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2NotEqualTo(String value) {
			addCriterion("ADDRESS2 <>", value, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2GreaterThan(String value) {
			addCriterion("ADDRESS2 >", value, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2GreaterThanOrEqualTo(String value) {
			addCriterion("ADDRESS2 >=", value, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2LessThan(String value) {
			addCriterion("ADDRESS2 <", value, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2LessThanOrEqualTo(String value) {
			addCriterion("ADDRESS2 <=", value, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2Like(String value) {
			addCriterion("ADDRESS2 like", value, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2NotLike(String value) {
			addCriterion("ADDRESS2 not like", value, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2In(List<String> values) {
			addCriterion("ADDRESS2 in", values, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2NotIn(List<String> values) {
			addCriterion("ADDRESS2 not in", values, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2Between(String value1, String value2) {
			addCriterion("ADDRESS2 between", value1, value2, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2NotBetween(String value1, String value2) {
			addCriterion("ADDRESS2 not between", value1, value2, "address2");
			return (Criteria) this;
		}

		public Criteria andCityIsNull() {
			addCriterion("CITY is null");
			return (Criteria) this;
		}

		public Criteria andCityIsNotNull() {
			addCriterion("CITY is not null");
			return (Criteria) this;
		}

		public Criteria andCityEqualTo(String value) {
			addCriterion("CITY =", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotEqualTo(String value) {
			addCriterion("CITY <>", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThan(String value) {
			addCriterion("CITY >", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThanOrEqualTo(String value) {
			addCriterion("CITY >=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThan(String value) {
			addCriterion("CITY <", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThanOrEqualTo(String value) {
			addCriterion("CITY <=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLike(String value) {
			addCriterion("CITY like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotLike(String value) {
			addCriterion("CITY not like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityIn(List<String> values) {
			addCriterion("CITY in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotIn(List<String> values) {
			addCriterion("CITY not in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityBetween(String value1, String value2) {
			addCriterion("CITY between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotBetween(String value1, String value2) {
			addCriterion("CITY not between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andPostCodeIsNull() {
			addCriterion("POST_CODE is null");
			return (Criteria) this;
		}

		public Criteria andPostCodeIsNotNull() {
			addCriterion("POST_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andPostCodeEqualTo(String value) {
			addCriterion("POST_CODE =", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeNotEqualTo(String value) {
			addCriterion("POST_CODE <>", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeGreaterThan(String value) {
			addCriterion("POST_CODE >", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeGreaterThanOrEqualTo(String value) {
			addCriterion("POST_CODE >=", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeLessThan(String value) {
			addCriterion("POST_CODE <", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeLessThanOrEqualTo(String value) {
			addCriterion("POST_CODE <=", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeLike(String value) {
			addCriterion("POST_CODE like", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeNotLike(String value) {
			addCriterion("POST_CODE not like", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeIn(List<String> values) {
			addCriterion("POST_CODE in", values, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeNotIn(List<String> values) {
			addCriterion("POST_CODE not in", values, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeBetween(String value1, String value2) {
			addCriterion("POST_CODE between", value1, value2, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeNotBetween(String value1, String value2) {
			addCriterion("POST_CODE not between", value1, value2, "postCode");
			return (Criteria) this;
		}

		public Criteria andCountryIsNull() {
			addCriterion("COUNTRY is null");
			return (Criteria) this;
		}

		public Criteria andCountryIsNotNull() {
			addCriterion("COUNTRY is not null");
			return (Criteria) this;
		}

		public Criteria andCountryEqualTo(String value) {
			addCriterion("COUNTRY =", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotEqualTo(String value) {
			addCriterion("COUNTRY <>", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryGreaterThan(String value) {
			addCriterion("COUNTRY >", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryGreaterThanOrEqualTo(String value) {
			addCriterion("COUNTRY >=", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryLessThan(String value) {
			addCriterion("COUNTRY <", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryLessThanOrEqualTo(String value) {
			addCriterion("COUNTRY <=", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryLike(String value) {
			addCriterion("COUNTRY like", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotLike(String value) {
			addCriterion("COUNTRY not like", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryIn(List<String> values) {
			addCriterion("COUNTRY in", values, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotIn(List<String> values) {
			addCriterion("COUNTRY not in", values, "country");
			return (Criteria) this;
		}

		public Criteria andCountryBetween(String value1, String value2) {
			addCriterion("COUNTRY between", value1, value2, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotBetween(String value1, String value2) {
			addCriterion("COUNTRY not between", value1, value2, "country");
			return (Criteria) this;
		}

		public Criteria andRegionIsNull() {
			addCriterion("REGION is null");
			return (Criteria) this;
		}

		public Criteria andRegionIsNotNull() {
			addCriterion("REGION is not null");
			return (Criteria) this;
		}

		public Criteria andRegionEqualTo(String value) {
			addCriterion("REGION =", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionNotEqualTo(String value) {
			addCriterion("REGION <>", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionGreaterThan(String value) {
			addCriterion("REGION >", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionGreaterThanOrEqualTo(String value) {
			addCriterion("REGION >=", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionLessThan(String value) {
			addCriterion("REGION <", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionLessThanOrEqualTo(String value) {
			addCriterion("REGION <=", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionLike(String value) {
			addCriterion("REGION like", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionNotLike(String value) {
			addCriterion("REGION not like", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionIn(List<String> values) {
			addCriterion("REGION in", values, "region");
			return (Criteria) this;
		}

		public Criteria andRegionNotIn(List<String> values) {
			addCriterion("REGION not in", values, "region");
			return (Criteria) this;
		}

		public Criteria andRegionBetween(String value1, String value2) {
			addCriterion("REGION between", value1, value2, "region");
			return (Criteria) this;
		}

		public Criteria andRegionNotBetween(String value1, String value2) {
			addCriterion("REGION not between", value1, value2, "region");
			return (Criteria) this;
		}

		public Criteria andMakeIpIsNull() {
			addCriterion("MAKE_IP is null");
			return (Criteria) this;
		}

		public Criteria andMakeIpIsNotNull() {
			addCriterion("MAKE_IP is not null");
			return (Criteria) this;
		}

		public Criteria andMakeIpEqualTo(String value) {
			addCriterion("MAKE_IP =", value, "makeIp");
			return (Criteria) this;
		}

		public Criteria andMakeIpNotEqualTo(String value) {
			addCriterion("MAKE_IP <>", value, "makeIp");
			return (Criteria) this;
		}

		public Criteria andMakeIpGreaterThan(String value) {
			addCriterion("MAKE_IP >", value, "makeIp");
			return (Criteria) this;
		}

		public Criteria andMakeIpGreaterThanOrEqualTo(String value) {
			addCriterion("MAKE_IP >=", value, "makeIp");
			return (Criteria) this;
		}

		public Criteria andMakeIpLessThan(String value) {
			addCriterion("MAKE_IP <", value, "makeIp");
			return (Criteria) this;
		}

		public Criteria andMakeIpLessThanOrEqualTo(String value) {
			addCriterion("MAKE_IP <=", value, "makeIp");
			return (Criteria) this;
		}

		public Criteria andMakeIpLike(String value) {
			addCriterion("MAKE_IP like", value, "makeIp");
			return (Criteria) this;
		}

		public Criteria andMakeIpNotLike(String value) {
			addCriterion("MAKE_IP not like", value, "makeIp");
			return (Criteria) this;
		}

		public Criteria andMakeIpIn(List<String> values) {
			addCriterion("MAKE_IP in", values, "makeIp");
			return (Criteria) this;
		}

		public Criteria andMakeIpNotIn(List<String> values) {
			addCriterion("MAKE_IP not in", values, "makeIp");
			return (Criteria) this;
		}

		public Criteria andMakeIpBetween(String value1, String value2) {
			addCriterion("MAKE_IP between", value1, value2, "makeIp");
			return (Criteria) this;
		}

		public Criteria andMakeIpNotBetween(String value1, String value2) {
			addCriterion("MAKE_IP not between", value1, value2, "makeIp");
			return (Criteria) this;
		}

		public Criteria andMakeTimeIsNull() {
			addCriterion("MAKE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andMakeTimeIsNotNull() {
			addCriterion("MAKE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andMakeTimeEqualTo(Date value) {
			addCriterion("MAKE_TIME =", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeNotEqualTo(Date value) {
			addCriterion("MAKE_TIME <>", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeGreaterThan(Date value) {
			addCriterion("MAKE_TIME >", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("MAKE_TIME >=", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeLessThan(Date value) {
			addCriterion("MAKE_TIME <", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeLessThanOrEqualTo(Date value) {
			addCriterion("MAKE_TIME <=", value, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeIn(List<Date> values) {
			addCriterion("MAKE_TIME in", values, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeNotIn(List<Date> values) {
			addCriterion("MAKE_TIME not in", values, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeBetween(Date value1, Date value2) {
			addCriterion("MAKE_TIME between", value1, value2, "makeTime");
			return (Criteria) this;
		}

		public Criteria andMakeTimeNotBetween(Date value1, Date value2) {
			addCriterion("MAKE_TIME not between", value1, value2, "makeTime");
			return (Criteria) this;
		}

		public Criteria andModifyEmpIsNull() {
			addCriterion("MODIFY_EMP is null");
			return (Criteria) this;
		}

		public Criteria andModifyEmpIsNotNull() {
			addCriterion("MODIFY_EMP is not null");
			return (Criteria) this;
		}

		public Criteria andModifyEmpEqualTo(Integer value) {
			addCriterion("MODIFY_EMP =", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpNotEqualTo(Integer value) {
			addCriterion("MODIFY_EMP <>", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpGreaterThan(Integer value) {
			addCriterion("MODIFY_EMP >", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpGreaterThanOrEqualTo(Integer value) {
			addCriterion("MODIFY_EMP >=", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpLessThan(Integer value) {
			addCriterion("MODIFY_EMP <", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpLessThanOrEqualTo(Integer value) {
			addCriterion("MODIFY_EMP <=", value, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpIn(List<Integer> values) {
			addCriterion("MODIFY_EMP in", values, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpNotIn(List<Integer> values) {
			addCriterion("MODIFY_EMP not in", values, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpBetween(Integer value1, Integer value2) {
			addCriterion("MODIFY_EMP between", value1, value2, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyEmpNotBetween(Integer value1, Integer value2) {
			addCriterion("MODIFY_EMP not between", value1, value2, "modifyEmp");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("MODIFY_TIME is null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("MODIFY_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualTo(Date value) {
			addCriterion("MODIFY_TIME =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualTo(Date value) {
			addCriterion("MODIFY_TIME <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThan(Date value) {
			addCriterion("MODIFY_TIME >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("MODIFY_TIME >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThan(Date value) {
			addCriterion("MODIFY_TIME <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("MODIFY_TIME <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIn(List<Date> values) {
			addCriterion("MODIFY_TIME in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotIn(List<Date> values) {
			addCriterion("MODIFY_TIME not in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeBetween(Date value1, Date value2) {
			addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andVerIsNull() {
			addCriterion("VER is null");
			return (Criteria) this;
		}

		public Criteria andVerIsNotNull() {
			addCriterion("VER is not null");
			return (Criteria) this;
		}

		public Criteria andVerEqualTo(Integer value) {
			addCriterion("VER =", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotEqualTo(Integer value) {
			addCriterion("VER <>", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerGreaterThan(Integer value) {
			addCriterion("VER >", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerGreaterThanOrEqualTo(Integer value) {
			addCriterion("VER >=", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerLessThan(Integer value) {
			addCriterion("VER <", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerLessThanOrEqualTo(Integer value) {
			addCriterion("VER <=", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerIn(List<Integer> values) {
			addCriterion("VER in", values, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotIn(List<Integer> values) {
			addCriterion("VER not in", values, "ver");
			return (Criteria) this;
		}

		public Criteria andVerBetween(Integer value1, Integer value2) {
			addCriterion("VER between", value1, value2, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotBetween(Integer value1, Integer value2) {
			addCriterion("VER not between", value1, value2, "ver");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbg.generated do_not_delete_during_merge Sun Jun 04 04:33:05 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}