package com.catike_mall.domain.entity.normal;

import java.util.Date;

public class UserInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.PK_ID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer pkId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.USERNAME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.PASSWORD
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.ENABLED
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Boolean enabled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.AUTHORITY
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String authority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.IMAGE_DIR
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String imageDir;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.FIRSTNAME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String firstname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.LASTNAME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String lastname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.EMAIL
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.TELEPHONE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.FAX
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String fax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.COMPANY
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String company;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.ADDRESS1
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String address1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.ADDRESS2
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String address2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.CITY
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.POST_CODE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String postCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.COUNTRY
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String country;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.REGION
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String region;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.MAKE_IP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private String makeIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.MAKE_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Date makeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.MODIFY_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer modifyEmp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.MODIFY_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.VER
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	private Integer ver;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.PK_ID
	 * @return  the value of user_info.PK_ID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getPkId() {
		return pkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.PK_ID
	 * @param pkId  the value for user_info.PK_ID
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setPkId(Integer pkId) {
		this.pkId = pkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.USERNAME
	 * @return  the value of user_info.USERNAME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.USERNAME
	 * @param username  the value for user_info.USERNAME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.PASSWORD
	 * @return  the value of user_info.PASSWORD
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.PASSWORD
	 * @param password  the value for user_info.PASSWORD
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.ENABLED
	 * @return  the value of user_info.ENABLED
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Boolean getEnabled() {
		return enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.ENABLED
	 * @param enabled  the value for user_info.ENABLED
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.AUTHORITY
	 * @return  the value of user_info.AUTHORITY
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getAuthority() {
		return authority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.AUTHORITY
	 * @param authority  the value for user_info.AUTHORITY
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setAuthority(String authority) {
		this.authority = authority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.IMAGE_DIR
	 * @return  the value of user_info.IMAGE_DIR
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getImageDir() {
		return imageDir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.IMAGE_DIR
	 * @param imageDir  the value for user_info.IMAGE_DIR
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setImageDir(String imageDir) {
		this.imageDir = imageDir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.FIRSTNAME
	 * @return  the value of user_info.FIRSTNAME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getFirstname() {
		return firstname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.FIRSTNAME
	 * @param firstname  the value for user_info.FIRSTNAME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.LASTNAME
	 * @return  the value of user_info.LASTNAME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getLastname() {
		return lastname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.LASTNAME
	 * @param lastname  the value for user_info.LASTNAME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.EMAIL
	 * @return  the value of user_info.EMAIL
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.EMAIL
	 * @param email  the value for user_info.EMAIL
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.TELEPHONE
	 * @return  the value of user_info.TELEPHONE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.TELEPHONE
	 * @param telephone  the value for user_info.TELEPHONE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.FAX
	 * @return  the value of user_info.FAX
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.FAX
	 * @param fax  the value for user_info.FAX
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.COMPANY
	 * @return  the value of user_info.COMPANY
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getCompany() {
		return company;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.COMPANY
	 * @param company  the value for user_info.COMPANY
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setCompany(String company) {
		this.company = company;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.ADDRESS1
	 * @return  the value of user_info.ADDRESS1
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getAddress1() {
		return address1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.ADDRESS1
	 * @param address1  the value for user_info.ADDRESS1
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.ADDRESS2
	 * @return  the value of user_info.ADDRESS2
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getAddress2() {
		return address2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.ADDRESS2
	 * @param address2  the value for user_info.ADDRESS2
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.CITY
	 * @return  the value of user_info.CITY
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.CITY
	 * @param city  the value for user_info.CITY
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.POST_CODE
	 * @return  the value of user_info.POST_CODE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getPostCode() {
		return postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.POST_CODE
	 * @param postCode  the value for user_info.POST_CODE
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.COUNTRY
	 * @return  the value of user_info.COUNTRY
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.COUNTRY
	 * @param country  the value for user_info.COUNTRY
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.REGION
	 * @return  the value of user_info.REGION
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getRegion() {
		return region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.REGION
	 * @param region  the value for user_info.REGION
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setRegion(String region) {
		this.region = region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.MAKE_IP
	 * @return  the value of user_info.MAKE_IP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public String getMakeIp() {
		return makeIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.MAKE_IP
	 * @param makeIp  the value for user_info.MAKE_IP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setMakeIp(String makeIp) {
		this.makeIp = makeIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.MAKE_TIME
	 * @return  the value of user_info.MAKE_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Date getMakeTime() {
		return makeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.MAKE_TIME
	 * @param makeTime  the value for user_info.MAKE_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setMakeTime(Date makeTime) {
		this.makeTime = makeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.MODIFY_EMP
	 * @return  the value of user_info.MODIFY_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getModifyEmp() {
		return modifyEmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.MODIFY_EMP
	 * @param modifyEmp  the value for user_info.MODIFY_EMP
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setModifyEmp(Integer modifyEmp) {
		this.modifyEmp = modifyEmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.MODIFY_TIME
	 * @return  the value of user_info.MODIFY_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.MODIFY_TIME
	 * @param modifyTime  the value for user_info.MODIFY_TIME
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.VER
	 * @return  the value of user_info.VER
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public Integer getVer() {
		return ver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.VER
	 * @param ver  the value for user_info.VER
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	public void setVer(Integer ver) {
		this.ver = ver;
	}
}