package com.catike_mall.dao.normal;

import com.catike_mall.domain.entity.normal.Advertise;
import com.catike_mall.domain.entity.normal.AdvertiseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdvertiseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table advertise
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	long countByExample(AdvertiseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table advertise
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int deleteByExample(AdvertiseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table advertise
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int deleteByPrimaryKey(Integer pkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table advertise
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int insert(Advertise record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table advertise
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int insertSelective(Advertise record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table advertise
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	List<Advertise> selectByExample(AdvertiseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table advertise
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	Advertise selectByPrimaryKey(Integer pkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table advertise
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int updateByExampleSelective(@Param("record") Advertise record, @Param("example") AdvertiseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table advertise
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int updateByExample(@Param("record") Advertise record, @Param("example") AdvertiseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table advertise
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int updateByPrimaryKeySelective(Advertise record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table advertise
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int updateByPrimaryKey(Advertise record);
}