package com.catike_mall.dao.normal;

import com.catike_mall.domain.entity.normal.InnerMail;
import com.catike_mall.domain.entity.normal.InnerMailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InnerMailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	long countByExample(InnerMailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int deleteByExample(InnerMailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int deleteByPrimaryKey(Integer pkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int insert(InnerMail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int insertSelective(InnerMail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	List<InnerMail> selectByExample(InnerMailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	InnerMail selectByPrimaryKey(Integer pkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int updateByExampleSelective(@Param("record") InnerMail record, @Param("example") InnerMailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int updateByExample(@Param("record") InnerMail record, @Param("example") InnerMailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int updateByPrimaryKeySelective(InnerMail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inner_mail
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int updateByPrimaryKey(InnerMail record);
}