package com.catike_mall.dao.normal;

import com.catike_mall.domain.entity.normal.StoreInfo;
import com.catike_mall.domain.entity.normal.StoreInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	long countByExample(StoreInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int deleteByExample(StoreInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int deleteByPrimaryKey(Integer pkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int insert(StoreInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int insertSelective(StoreInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	List<StoreInfo> selectByExample(StoreInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	StoreInfo selectByPrimaryKey(Integer pkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int updateByExampleSelective(@Param("record") StoreInfo record, @Param("example") StoreInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int updateByExample(@Param("record") StoreInfo record, @Param("example") StoreInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int updateByPrimaryKeySelective(StoreInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table store_info
	 * @mbg.generated  Sat Aug 26 17:34:55 EET 2017
	 */
	int updateByPrimaryKey(StoreInfo record);
}